# Site settings
title: AIUL - AI Usage License Project
email:
description: >-
  Standardizing AI usage in digital arts, empowering educators and students with clear AI usage guidelines.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Navigation
navigation:
  - {name: Home, link: '/'}
  - {name: Licenses, link: '/licenses.html'}
  - {name: Guide, link: '/guide.html'}
  - {name: Tag Generator, link: '/tag-generator.html'}
  - {name: Resources, link: '/resources.html'}

# Collections
collections:
  licenses:
    output: true
    sort_by: order
  modifiers:
    output: true
    sort_by: order