# Development-specific settings that override _config.yml
# Use empty baseurl for local development
baseurl: ""

# Disable license image generation during development to prevent infinite loops
hooks:
  pre_build: []  # Disable hooks during development

# Exclude from processing - same as main config plus scripts folder
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - scripts/node_modules
  - scripts/temp.svg
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Files to ignore when watching for changes (prevents infinite regeneration loop)
# But still allow them to be copied to the destination
watch_exclude:
  - assets/images/licenses