# Site settings
title: AIUL - AI Usage License Project
email:
description: >-
  Standardizing AI usage in digital arts, empowering educators and students with clear AI usage guidelines.
baseurl: "/aiul" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Added hooks to run Node.js script for generating license images
hooks:
  pre_build:
    - scripts/generate-license-images.js

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - scripts/node_modules
  - scripts/temp.svg
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Files to ignore when watching for changes (prevents infinite regeneration loop)
# But still allow them to be copied to the destination
watch_exclude:
  - assets/images/licenses

# Navigation
navigation:
  - {name: Home, link: '/'}
  - {name: Licenses, link: '/licenses.html'}
  - {name: Guide, link: '/guide.html'}
  - {name: Tag Generator, link: '/tag-generator.html'}
  - {name: Resources, link: '/resources.html'}

# Collections
collections:
  licenses:
    output: true
    sort_by: order
    permalink: /licenses/:name:output_ext
  modifiers:
    output: true
    sort_by: order
    permalink: /modifiers/:name:output_ext